import assert from 'node:assert/strict';
import {readFile,readdir,writeFile,mkdir} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
const base=process.env.E2E_BASE_URL||'http://127.0.0.1:18080';
if(!process.env.E2E_ALLOW_MUTATIONS||new URL(base).port!=='18080')throw Error('Run only against the isolated test gateway on port 18080 with E2E_ALLOW_MUTATIONS=1.');
const results=[],calls=[],expected=[];let throttles=0;
for(const file of await readdir('backend/src/main/java/com/example/backend')){if(!file.endsWith('Controller.java'))continue;const src=await readFile('backend/src/main/java/com/example/backend/'+file,'utf8');const cls=src.indexOf('public class');const prefix=src.slice(0,cls).match(/@RequestMapping\("([^"]+)"\)/)?.[1]||'';for(const m of src.matchAll(/@(Get|Post|Put|Patch|Delete|Request)Mapping(?:\((?:value=)?"([^"]+)"[^)]*\))?/g)){if(m.index<cls)continue;const path=prefix+(m[2]||'');expected.push({method:m[1]==='Request'?'*':m[1].toUpperCase(),path});}}
async function req(method,path,token,body,status=200,headers={}){let r;for(let n=0;n<15;n++){r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===429&&path.startsWith('/api/auth/')&&status!==429){throttles++;await r.text();await delay(5100);continue;}break;}const text=await r.text();let data;try{data=JSON.parse(text);}catch{data=text;}calls.push({method,path:path.replace(/[0-9a-f]{8}-[0-9a-f-]{27,}/g,'{id}'),status:r.status,expected:status});assert.equal(r.status,status,method+' '+path+' expected '+status+' got '+r.status+' '+(data?.code||''));return {data,response:r};}
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message});throw e;}}
const pass='SentinelX-Local-2026!',newPass='Verified-password-2026!';
const login=async(email,password=pass)=>(await req('POST','/api/auth/login',null,{email,password})).data;
let admin,dev,operator,user,createdId,createdToken,key,secondKey,service,instance,route,rate,createdEmail='final-'+Date.now()+'@example.test';
try{
 await check('Public health, embedded frontend and static assets',async()=>{assert.equal((await req('GET','/health')).data.status,'UP');for(const p of ['/','/index.html','/app.js','/style.css','/favicon.svg'])await req('GET',p);});
 await check('Four role sign-ins and authenticated profiles',async()=>{admin=await login('admin@sentinelx.local');operator=await login('operator@sentinelx.local');dev=await login('developer@sentinelx.local');user=await login('user@sentinelx.local');for(const a of [admin,operator,dev,user]){assert.equal((await req('GET','/api/me',a.token)).data.role,a.user.role);assert.ok((await req('GET','/api/me/sessions',a.token)).data.length>0);}});
 await check('Anonymous, user, developer and operator authorization boundaries',async()=>{await req('GET','/api/me',null,undefined,401);for(const a of [user,dev,operator])await req('GET','/api/admin/users',a.token,undefined,403);for(const a of [user,dev])await req('GET','/api/ops/services',a.token,undefined,403);for(const a of [user,operator])await req('POST','/api/me/keys',a.token,{name:'Forbidden',days:1},403);await req('GET','/gateway/users',user.token,undefined,403);await req('GET','/gateway/users',null,undefined,401);});
 await check('Operator monitoring endpoints and active health check',async()=>{await req('POST','/api/ops/check-health',operator.token);for(const p of ['services','instances','routes','rate-limits','circuits','metrics','logs'])await req('GET','/api/ops/'+p,operator.token);assert.ok((await req('GET','/api/ops/instances',operator.token)).data.every(i=>i.status==='HEALTHY'));});
 await check('Registration, validation and persistent profile update',async()=>{await req('POST','/api/auth/register',null,{name:'Invalid',email:'bad',password:pass,confirmPassword:pass},400);const account=(await req('POST','/api/auth/register',null,{name:'Verification Account',email:createdEmail,password:pass,confirmPassword:pass})).data;createdId=account.id;createdToken=(await login(createdEmail)).token;await req('PATCH','/api/me',createdToken,{name:'Verified Account'});assert.equal((await req('GET','/api/me',createdToken)).data.name,'Verified Account');await req('PATCH','/api/me',createdToken,{name:''},400);});
 await check('API catalog, forwarding, correlation and CRUD on single-instance demo resources',async()=>{assert.equal((await req('GET','/api/me/apis',dev.token)).data.length,3);for(const path of ['/users','/products','/orders']){const r=await req('GET','/gateway'+path,dev.token,undefined,200,{'X-Request-ID':'final-e2e-request'});assert.equal(r.response.headers.get('X-Request-ID'),'final-e2e-request');}for(const resource of ['products','orders']){const item=(await req('POST','/gateway/'+resource,dev.token,{name:'Isolated gateway verification'},201)).data;assert.equal((await req('GET','/gateway/'+resource+'/'+item.id,dev.token)).data.name,'Isolated gateway verification');}await req('GET','/gateway/not-configured',dev.token,undefined,404);await req('DELETE','/gateway/products',dev.token,undefined,404);});
 await check('Key creation, ownership, disable/enable, rotation and revocation',async()=>{key=(await req('POST','/api/me/keys',dev.token,{name:'Final verification',days:1})).data;const list=(await req('GET','/api/me/keys',dev.token)).data;assert.ok(list.some(k=>k.id===key.id));assert.ok(!JSON.stringify(list).includes(key.secret));await req('GET','/gateway/users',null,undefined,200,{'X-API-Key':key.secret});await req('PATCH','/api/me/keys/'+key.id,user.token,{active:false},404);await req('PATCH','/api/me/keys/'+key.id,dev.token,{active:false});await req('GET','/gateway/users',null,undefined,401,{'X-API-Key':key.secret});await req('PATCH','/api/me/keys/'+key.id,dev.token,{active:true});await req('GET','/gateway/users',null,undefined,200,{'X-API-Key':key.secret});const old=key;key=(await req('POST','/api/me/keys/'+key.id+'/rotate',dev.token)).data;await req('GET','/gateway/users',null,undefined,401,{'X-API-Key':old.secret});await req('GET','/gateway/users',null,undefined,200,{'X-API-Key':key.secret});await req('DELETE','/api/me/keys/'+key.id,dev.token);await req('GET','/gateway/users',null,undefined,401,{'X-API-Key':key.secret});});
 await check('Administrator consumer inspection, tier update and revocation',async()=>{secondKey=(await req('POST','/api/me/keys',dev.token,{name:'Consumer verification',days:1})).data;await req('PATCH','/api/admin/consumers/'+secondKey.id,admin.token,{tier:'ELEVATED',active:true});const consumers=(await req('GET','/api/admin/consumers',admin.token)).data;assert.equal(consumers.find(k=>k.id===secondKey.id).tier,'ELEVATED');await req('DELETE','/api/admin/consumers/'+secondKey.id,admin.token);await req('GET','/gateway/users',null,undefined,401,{'X-API-Key':secondKey.secret});});
 await check('Administrator service and instance lifecycle with origin validation',async()=>{service=(await req('POST','/api/admin/services',admin.token,{name:'verification-service',strategy:'ROUND_ROBIN',enabled:true})).data.id;await req('PUT','/api/admin/services/'+service,admin.token,{name:'verification-service',strategy:'LEAST_CONNECTIONS',enabled:true});await req('POST','/api/admin/instances',admin.token,{serviceId:service,baseUrl:'http://169.254.169.254',healthPath:'/health',enabled:true},400);instance=(await req('POST','/api/admin/instances',admin.token,{serviceId:service,baseUrl:'http://localhost:9102',healthPath:'/health',enabled:true})).data.id;await req('POST','/api/ops/check-health',operator.token);assert.equal((await req('GET','/api/ops/instances',operator.token)).data.find(i=>i.id===instance).status,'HEALTHY');});
 await check('Dynamic route creation, update, method matching and removal',async()=>{const body={pathPrefix:'/verify',methods:'GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS',serviceId:service,enabled:true,timeoutMs:2000,connectTimeoutMs:500,readTimeoutMs:1000,retries:0,backoffMs:0,failureThreshold:3,recoveryMs:500};route=(await req('POST','/api/admin/routes',admin.token,body)).data.id;for(const method of ['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS']){const r=await req(method,'/gateway/verify',dev.token,undefined,404);assert.ok(r.response.headers.get('X-SentinelX-Instance'),'Matched route should reach upstream even when its resource is absent');}await req('PUT','/api/admin/routes/'+route,admin.token,{...body,enabled:false});await req('GET','/gateway/verify',dev.token,undefined,404);await req('DELETE','/api/admin/routes/'+route,admin.token);await req('DELETE','/api/admin/instances/'+instance,admin.token);await req('DELETE','/api/admin/services/'+service,admin.token);assert.ok(!(await req('GET','/api/ops/services',admin.token)).data.some(s=>s.id===service));});
 await check('Rate-limit create/update, real rejection, deletion and quota read',async()=>{rate=(await req('POST','/api/admin/rate-limits',admin.token,{scope:'KEY',capacity:2,refillPerSecond:0.001,enabled:true})).data.id;await req('PUT','/api/admin/rate-limits/'+rate,admin.token,{scope:'KEY',capacity:1,refillPerSecond:0.001,enabled:true});const k=(await req('POST','/api/me/keys',dev.token,{name:'Rate verification',days:1})).data;await req('GET','/gateway/products',null,undefined,200,{'X-API-Key':k.secret});const limited=await req('GET','/gateway/products',null,undefined,429,{'X-API-Key':k.secret});assert.ok(limited.response.headers.get('Retry-After'));await req('DELETE','/api/admin/rate-limits/'+rate,admin.token);await req('GET','/gateway/products',null,undefined,200,{'X-API-Key':k.secret});await req('GET','/api/me/quotas',dev.token);await req('DELETE','/api/me/keys/'+k.id,dev.token);});
 await check('Own traffic isolation, metrics and administrator audit trail',async()=>{assert.ok((await req('GET','/api/me/metrics',dev.token)).data.total>0);assert.equal((await req('GET','/api/me/metrics',user.token)).data.total,0);assert.equal((await req('GET','/api/me/requests',user.token)).data.length,0);assert.ok((await req('GET','/api/me/requests',dev.token)).data.length>0);assert.ok((await req('GET','/api/admin/audit',admin.token)).data.some(a=>a.action==='ADMIN_CREATED_SERVICE'));});
 await check('Admin user changes, forced logout and blocked self-demotion',async()=>{await req('GET','/api/admin/users',admin.token);await req('PATCH','/api/admin/users/'+admin.user.id,admin.token,{role:'USER',active:true,apiEnabled:true},400);await req('PATCH','/api/admin/users/'+createdId,admin.token,{role:'USER',active:true,apiEnabled:false});await req('GET','/api/me',createdToken,undefined,401);createdToken=(await login(createdEmail)).token;assert.equal((await req('GET','/api/me',createdToken)).data.role,'USER');await req('POST','/api/admin/users/'+createdId+'/force-logout',admin.token);await req('GET','/api/me',createdToken,undefined,401);});
 await check('Forced password reset, mailbox delivery and single-use reset link',async()=>{await req('POST','/api/admin/users/'+createdId+'/force-reset',admin.token);await req('POST','/api/auth/login',null,{email:createdEmail,password:pass},403);await req('POST','/api/auth/forgot-password',null,{email:createdEmail});const mail=await readFile('work/final-e2e-mailbox/'+createdId+'.txt','utf8');const reset=mail.split('#reset/')[1].trim();await req('POST','/api/auth/reset-password',null,{token:reset,password:newPass,confirmPassword:newPass});await req('POST','/api/auth/reset-password',null,{token:reset,password:newPass,confirmPassword:newPass},400);createdToken=(await login(createdEmail,newPass)).token;});
 await check('Password change, all-session revocation and logout',async()=>{await req('POST','/api/auth/change-password',createdToken,{currentPassword:newPass,password:pass,confirmPassword:pass});await req('GET','/api/me',createdToken,undefined,401);const a=await login(createdEmail),b=await login(createdEmail);await req('POST','/api/auth/logout-all',a.token);await req('GET','/api/me',b.token,undefined,401);await req('POST','/api/auth/logout',dev.token);await req('GET','/api/me',dev.token,undefined,401);});
}finally{
 const coverage=expected.map(e=>({...e,covered:calls.some(c=>(e.method==='*'||e.method===c.method)&&new RegExp('^'+e.path.replaceAll('**','.*').replaceAll('{id}','[^/]+')+'$').test(c.path))}));
 await mkdir('docs/validation',{recursive:true});await writeFile('docs/validation/final-api-results.json',JSON.stringify({timestamp:new Date().toISOString(),base,results,calls,coverage,authThrottleResponses:throttles},null,2));
 console.log('Endpoint coverage '+coverage.filter(e=>e.covered).length+'/'+coverage.length);
 if(results.every(r=>r.status==='PASS'))assert.ok(coverage.every(e=>e.covered),'All implemented endpoint mappings must be exercised');
}

