import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:8080';const label=process.env.SMOKE_LABEL||'native';const results=[];
async function call(path,token,method='GET',body,extra={}){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...extra},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {response,data};}
async function check(name,action){await action();results.push({name,status:'PASS'});console.log('PASS '+name);}
let admin,developer,key;
try{
 await check('Gateway and embedded frontend available',async()=>{assert.equal((await call('/health')).data.status,'UP');const page=await call('/');assert.equal(page.response.status,200);assert.match(page.data,/SentinelX/);assert.equal((await call('/app.js')).response.status,200);});
 await check('Admin and developer sign-in',async()=>{for(const role of ['admin','developer']){const login=await call('/api/auth/login',null,'POST',{email:role+'@sentinelx.local',password:process.env.DEMO_PASSWORD||'SentinelX-Local-2026!'});assert.equal(login.response.status,200);if(role==='admin')admin=login.data.token;else developer=login.data.token;}});
 await check('Backend role authorization and safe user list',async()=>{assert.equal((await call('/api/admin/users',developer)).response.status,403);const users=await call('/api/admin/users',admin);assert.equal(users.response.status,200);assert.ok(users.data.length>=4);assert.ok(!JSON.stringify(users.data).includes('password_hash'));});
 await check('All four upstream instances healthy',async()=>{await call('/api/ops/check-health',admin,'POST');const instances=(await call('/api/ops/instances',admin)).data;assert.equal(instances.length,4);assert.ok(instances.every(i=>i.status==='HEALTHY'));});
 await check('Create API key and distribute requests',async()=>{const created=await call('/api/me/keys',developer,'POST',{name:label+' smoke test',days:1});assert.equal(created.response.status,200);key=created.data;const seen=new Set();for(let i=0;i<6;i++){const r=await call('/gateway/users',null,'GET',undefined,{'X-API-Key':key.secret,'X-Request-ID':'smoke-'+i});assert.equal(r.response.status,200);assert.equal(r.response.headers.get('X-Request-ID'),'smoke-'+i);seen.add(r.data.instance);}assert.equal(seen.size,2);});
 await check('Product and order forwarding and product CRUD',async()=>{for(const path of ['/gateway/products','/gateway/orders'])assert.equal((await call(path,developer)).response.status,200);const created=await call('/gateway/products',developer,'POST',{name:'Smoke product'});assert.equal(created.response.status,201);const read=await call('/gateway/products/'+created.data.id,developer);assert.equal(read.response.status,200);assert.equal(read.data.name,'Smoke product');});
 await check('Metrics, logs and quota reflect real requests',async()=>{const m=(await call('/api/me/metrics',developer)).data;assert.ok(m.total>=10);const logs=(await call('/api/me/requests',developer)).data;assert.ok(logs.length>=10);assert.ok(logs.some(x=>x.path==='/products'));assert.ok(Array.isArray((await call('/api/me/quotas',developer)).data));});
 await check('Rotation revokes old secret and activates new secret',async()=>{const old=key.secret;const rotated=await call('/api/me/keys/'+key.id+'/rotate',developer,'POST');assert.equal(rotated.response.status,200);key=rotated.data;assert.equal((await call('/gateway/users',null,'GET',undefined,{'X-API-Key':old})).response.status,401);assert.equal((await call('/gateway/users',null,'GET',undefined,{'X-API-Key':key.secret})).response.status,200);});
 await check('Revocation invalidates API key',async()=>{await call('/api/me/keys/'+key.id,developer,'DELETE');assert.equal((await call('/gateway/users',null,'GET',undefined,{'X-API-Key':key.secret})).response.status,401);});
 await check('Logout invalidates the session',async()=>{await call('/api/auth/logout',developer,'POST');assert.equal((await call('/api/me',developer)).response.status,401);developer=null;});
}finally{
 if(developer&&key)await call('/api/me/keys/'+key.id,developer,'DELETE');
 if(developer)await call('/api/auth/logout',developer,'POST');if(admin)await call('/api/auth/logout',admin,'POST');
 await mkdir('docs/validation',{recursive:true});await writeFile('docs/validation/'+label+'-smoke.json',JSON.stringify({timestamp:new Date().toISOString(),base,results},null,2));
}
